server {
    listen 80;

    ## Multi-domain support:
    #server_name localhost example.com www.example.com;
    ## Common practice when running behind a reverse proxy or load balancer,
    ## '_' This means match any hostname.
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /static/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
      }

    error_page 500 502 503 504 /50x.html;
}