# =========================
# Build stage
# =========================
FROM maven:3.9-eclipse-temurin-17 AS build
LABEL authors="towhid.islam"
MAINTAINER ${authors}

ENV HOME=/app
RUN mkdir -p $HOME
WORKDIR $HOME
# Copy pom first (better layer caching)
COPY pom.xml .
# Copy source and build
COPY src src

# Run mvn cmd
RUN mvn clean package -DskipTests -Pproduction

# =========================
# Runtime stage
# =========================
#FROM eclipse-temurin:21-jre-alpine
#FROM eclipse-temurin:17-jre-alpine
FROM eclipse-temurin:17-jre
LABEL authors="towhid.islam"
MAINTAINER ${authors}

ENV HOME=/app
RUN mkdir -p $HOME
WORKDIR $HOME
# Copy the built JAR from build stage
COPY --from=build /app/target/*.jar app.jar

# Expose Spring Boot default port
EXPOSE 8080

# Optional: reduce memory footprint
ENV JAVA_OPTS="-XX:MaxRAMPercentage=75"

ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar"]
#ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS -jar app.jar --spring.profiles.active=dev"]